# This file was generated by the {rix} R package v0.6.0 on 2024-03-19
# with following call:
# >rix::rix(r_ver = "5710127d9693421e78cca4f74fac2db6d67162b1",
#  > r_pkgs = c(pkgs_dev,
#  > pkgs_projj) %>% unique() %>% sort(),
#  > system_pkgs = pkgs_sys %>% unique() %>% sort(),
#  > git_pkgs = NULL,
#  > ide = c("other",
#  > "code",
#  > "rstudio")[1],
#  > project_path = path_default_nix,
#  > overwrite = TRUE,
#  > print = FALSE,
#  > shell_hook = paste("export R_LIBS_USER=_R_LIBS_USER &&",
#  > shell_hook))
# It uses nixpkgs' revision 5710127d9693421e78cca4f74fac2db6d67162b1 for reproducibility purposes
# which will install R version latest
# Report any issues to https://github.com/b-rodrigues/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/5710127d9693421e78cca4f74fac2db6d67162b1.tar.gz") {};
 rpkgs = builtins.attrValues {
  inherit (pkgs.rPackages) Cairo devtools dplyr fs getPass ggplot2 glue goodpractice here httpgd httr lubridate pacman purrr quarto R6 readr reticulate rmarkdown rvest stringr tarchetypes targets tidyr visNetwork xml2 zoo;
};
   system_packages = builtins.attrValues {
  inherit (pkgs) R glibcLocales nix cairo lazygit nano oh-my-zsh openssl quarto radianWrapper;
};
  in
  pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then  "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";

    buildInputs = [  rpkgs  system_packages  ];
      shellHook = "export R_LIBS_USER=_R_LIBS_USER && ";
  }
