---
params:
  title: "reactiveValues() & oberve() (not reactive())"
  source_git: "https://github.com/AlbertRapp/3mw_newsletters/blob/master/82_Jun_19_2024/82_Jun_19_2024.qmd"
  source_website: "https://3mw.albert-rapp.de/p/share-data-across-modules"
title: "`r params$title`"
theme: ../theme.scss
format: 
  html: 
    fig-height: 5
    fig-dpi: 300
    fig-width: 8.88
    fig-align: center
knitr: 
  opts_chunk: 
    collapse: true
---

## Dump code to into app.R
```{r knitr purl, eval = FALSE}
library(here)
fn_in <- here("inst", "qmd", "share-data-across-modules", "share-data-across-modules.qmd")
fn_out <- here("inst", "qmd", "share-data-across-modules", "share-data-across-modules.R")
knitr::purl(input = fn_in, output = fn_out, documentation = 0)
```

## Setup

```{r Setup}
# setwd(here::here('82_Jun_19_2024'))
library(tidyverse)

theme_set(
  theme_minimal(
    base_size = 16,
    base_family = 'Source Sans Pro'
  ) +
    theme(panel.grid.minor = element_blank())
) 
```

## shinyApp 1

```{r}
#| eval: false
library(shiny)
ui <- bslib::page_fluid(
  selectInput(
      "dropdown", 
      "Choose a chart", 
      choices = c("bar", "boxplot")
  ),
  plot_UI("plot")
)
```



```{r}
#| eval: false
library(ggplot2)
plot_UI <- function(id) {
  ns <- NS(id)
  tagList(
    plotOutput(ns("plot"))
  )
}

plot_Server <- function(id, dropdown_choice) {
  moduleServer(
    id,
    function(input, output, session) {
      output$plot <- renderPlot({
        if (dropdown_choice == "bar") {
          
          p <- ggplot(
            mtcars, aes(x = factor(cyl))
          ) + 
            geom_bar(fill = 'dodgerblue4')
        
        } else {
          
          p <- ggplot(
            mtcars, aes(x = factor(cyl), y = mpg)
          ) + 
            geom_boxplot(
              color = 'dodgerblue4',
              linewidth = 1.5
            )
        
        }
        
        p +
          theme_minimal(base_size = 16)
      })
    }
  )
}
```




```{r server hard-code 2nd argument}
#| eval: false
server <- function(input, output, session) {
  plot_Server("plot", 'bar') # hard-code 2nd argument
}
shinyApp(ui, server)
```


## shinyApp 2

```{r server replace hard-coded argument}
#| eval: false
server <- function(input, output, session) {
  plot_Server(
    "plot", 
    input$dropdown # replace hard-coded argument
  ) 
}
shinyApp(ui, server)
```


## shinyApp 3

```{r}
#| eval: false
server <- function(input, output, session) {
  dropdown_choice <- reactive(input$dropdown)
  plot_Server(
    "plot", 
    dropdown_choice # pass reactive instead of value
  ) 
}
```


```{r}
#| eval: false
plot_Server <- function(id, dropdown_choice) {
  moduleServer(
    id,
    function(input, output, session) {
      
      output$plot <- renderPlot({
        # CALL REACTIVE HERE WITH ()
        if (dropdown_choice() == "bar") {
          
          p <- ggplot(
            mtcars, aes(x = factor(cyl))
          ) + 
            geom_bar(fill = 'dodgerblue4')
        
        } else {
          
          p <- ggplot(
            mtcars, aes(x = factor(cyl), y = mpg)
          ) + 
            geom_boxplot(
              color = 'dodgerblue4',
              linewidth = 1.5
            )
        
        }
        
        p +
          theme_minimal(base_size = 16)
      })
    }
  )
}

shinyApp(ui, server)
```


## shinyApp 4

```{r}
#| eval: false
server <- function(input, output, session) {
  # Use reactiveValues() instead of reactive()
  shared_data <- reactiveValues()
  observe({
     shared_data$dropdown_choice <- input$dropdown
  })
  
  plot_Server(
    "plot", 
    shared_data 
  ) 
}
```


```{r}
#| eval: false
# Rename argument to `shared_data` 
plot_Server <- function(id, shared_data) {
  moduleServer(
    id,
    function(input, output, session) {
      
      output$plot <- renderPlot({
        # Use new notation to access the value
        if (shared_data$dropdown_choice == "bar") {
          
          p <- ggplot(
            mtcars, aes(x = factor(cyl))
          ) + 
            geom_bar(fill = 'dodgerblue4')
        
        } else {
          
          p <- ggplot(
            mtcars, aes(x = factor(cyl), y = mpg)
          ) + 
            geom_boxplot(
              color = 'dodgerblue4',
              linewidth = 1.5
            )
        
        }
        
        p +
          theme_minimal(base_size = 16)
      })
    }
  )
}

shinyApp(ui, server)
```
