# This file was generated by the {rix} R package v0.6.0 on 2024-05-23
# with following call:
# >rix::rix(r_ver = "3f316d2a50699a78afe5e77ca486ad553169061e",
#  > r_pkgs = c(pkgs_dev_min,
#  > pkgs_proj) %>% unique() %>% sort(),
#  > system_pkgs = pkgs_sys %>% unique() %>% sort(),
#  > git_pkgs = pkgs_git,
#  > ide = c("other",
#  > "code",
#  > "rstudio")[1],
#  > project_path = path_default_nix,
#  > overwrite = TRUE,
#  > print = FALSE,
#  > shell_hook = shell_hook)
# It uses nixpkgs' revision 3f316d2a50699a78afe5e77ca486ad553169061e for reproducibility purposes
# which will install R version latest
# Report any issues to https://github.com/b-rodrigues/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/3f316d2a50699a78afe5e77ca486ad553169061e.tar.gz") {};
 rpkgs = builtins.attrValues {
  inherit (pkgs.rPackages) devtools dplyr fs  ggplot2 glue goodpractice here  lubridate pacman purrr quarto readr reticulate rmarkdown rvest stringr tarchetypes targets tidyr ggiraph visNetwork ;
  # httpgd
};
 git_archive_pkgs = [(pkgs.rPackages.buildRPackage {
    name = "rix";
    src = pkgs.fetchgit {
      url = "https://github.com/b-rodrigues/rix";
      branchName = "master";
      rev = "6dcc9bcb10dcd1baaa9a7d83bab5d1445f231455";
      sha256 = "sha256-Gn0R4ND4AHE8wjtEEyHFI4Gl0p39nlb26VLRW16kClU=";
    };
    propagatedBuildInputs = builtins.attrValues {
      inherit (pkgs.rPackages) codetools httr jsonlite sys;
    };
  }) ];
  system_packages = builtins.attrValues {
  inherit (pkgs) R glibcLocales nix clang libffi nano oh-my-zsh openssl quarto radianWrapper readline;
};
  in
  pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then  "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";

    buildInputs = [ git_archive_pkgs rpkgs  system_packages  ];
      shellHook = "
  # export R_LIBS_USER='$(pwd)/_libs' &&
  export R_LIBS_USER= library  &&
    # Augment the dynamic linker path
    export LIBCLANG_PATH=${pkgs.libclang.lib}/ library  ;
   ";
  }
